# Generated by Django 5.2.5 on 2025-08-20 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('routeId', models.AutoField(primary_key=True, serialize=False)),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('start_date_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoutePreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_trains', models.BooleanField(blank=True, null=True)),
                ('allow_busses', models.BooleanField(blank=True, null=True)),
                ('allow_taxis', models.BooleanField(blank=True, null=True)),
                ('max_walk_distance', models.IntegerField(default=5000, verbose_name='Maximum Walk Distance (meters)')),
                ('routeId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route_preferences', to='planner.route')),
            ],
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_type', models.CharField(max_length=50)),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='planner.route')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_trains', models.BooleanField(blank=True, null=True)),
                ('allow_busses', models.BooleanField(blank=True, null=True)),
                ('allow_taxis', models.BooleanField(blank=True, null=True)),
                ('max_walk_distance', models.IntegerField(default=5000, verbose_name='Maximum Walk Distance (meters)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
